resources:
  Dbp\Relay\CabinetBundle\Entity\Group:
    types: ['https://schema.org/Organization']
    shortName: 'CabinetGroup'
    normalizationContext:
      groups: ['CabinetGroup:output']

    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\CabinetBundle\ApiPlatform\GroupProvider
        uriTemplate: '/cabinet/groups/{identifier}'
        openapiContext:
          tags: ["Cabinet"]

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\CabinetBundle\ApiPlatform\GroupProvider
        uriTemplate: '/cabinet/groups'
        openapiContext:
          tags: ['Cabinet']

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      street:
        iri: 'https://schema.org/streetAddress'
      locality:
        iri: 'https://schema.org/addressLocality'
      postalCode:
        iri: 'https://schema.org/postalCode'
      country:
        iri: 'https://schema.org/addressCountry'
      accessRights:
