services:
  Dbp\Relay\CabinetBundle\Service\CabinetService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_cabinet_bundle_entity_manager'

  Dbp\Relay\CabinetBundle\Service\BlobService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Controller\:
    tags: [ 'controller.service_arguments' ]
    resource: '../../Controller'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  dbp.relay.cabinet.cache.sync:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 60 }

  Dbp\Relay\CabinetBundle\TypesenseSync\TypesenseSync:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.cabinet.cache.sync' ]

  Dbp\Relay\CabinetBundle\TypesenseSync\DocumentTranslator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\SyncCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\SyncOneCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\DebugCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\UploadFileCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\DeleteFileCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\DeleteAllFilesCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Authorization\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\TypesenseSync\:
    resource: '../../TypesenseSync'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\TypesenseApi\:
    resource: '../../TypesenseApi'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Blob\:
    resource: '../../Blob'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\PersonSync\DummyPersonSync:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\PersonSync\PersonSyncInterface:
      '@Dbp\Relay\CabinetBundle\PersonSync\DummyPersonSync'
