services:
  Dbp\Relay\CabinetBundle\Service\CabinetService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_cabinet_bundle_entity_manager'

  Dbp\Relay\CabinetBundle\Service\BlobService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\SyncCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\SyncOneCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\UploadFileCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\DeleteFileCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\DeleteAllFilesCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Command\SetupCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Authorization\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\TypesenseSync\:
    resource: '../../TypesenseSync'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\TypesenseSync\TypesenseSync:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\TypesenseProxy\:
    resource: '../../TypesenseProxy'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\Blob\:
    resource: '../../Blob'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\PersonSync\DummyPersonSync:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\PersonSync\PersonSyncInterface:
      '@Dbp\Relay\CabinetBundle\PersonSync\DummyPersonSync'

  Dbp\Relay\CabinetBundle\FakeData\:
    resource: '../../FakeData'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetBundle\FakeData\FakeFileEvent:
    autowire: true
    autoconfigure: true